In [2]:
import numpy as np
numpy.__version__

'1.22.4'

## List -> Array

In [4]:
# create dense arrays of uniform type using built-in array module
import array
L = list(range(10))
A = array.array("i", L) # i for integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# create arrays from Python list
np.array([x for x in range(1, 11, 2)])

array([1, 3, 5, 7, 9])

In [6]:
# if some elements are of diff data type, np try tii upcast if possible
np.array([3.14, 2, 6, 9])

array([3.14, 2.  , 6.  , 9.  ])

In [12]:
# nested list -> mutlidimensional array
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Array from Scratch

In [19]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((5, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# create a (3, 6) array filled w/ 2.45
np.full((3, 6), 2.45)

array([[2.45, 2.45, 2.45, 2.45, 2.45, 2.45],
       [2.45, 2.45, 2.45, 2.45, 2.45, 2.45],
       [2.45, 2.45, 2.45, 2.45, 2.45, 2.45]])

In [23]:
# similar to range()
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [24]:
# 7 values evenly spaced between 2 numbers
np.linspace(0, 2.5, 7)

array([0.        , 0.41666667, 0.83333333, 1.25      , 1.66666667,
       2.08333333, 2.5       ])

In [26]:
# random float values
# random method from np.random module
np.random.random((3, 3))

array([[0.21972734, 0.68703754, 0.77050258],
       [0.67226234, 0.00675362, 0.02105429],
       [0.68409808, 0.54265667, 0.51290517]])

In [27]:
# random int values
np.random.randint(0, 10, (3, 3))

array([[8, 3, 6],
       [5, 5, 7],
       [2, 4, 3]])

In [28]:
# create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# create uninitialized array of 3 int
np.empty(3)

array([1., 1., 1.])

## Data Types in Numpy (dtype)
- bool_
- int_ (default int type; either in int64 or int32)
- intc
- ontp (int used for indexing)
- int8
- int16
- int32
- int64
- uint8 (unsigned int8)
- uint16
- uint32
- uint64
- float_
- float16
- float32
- float64
- complex_
- complex64
- complex128

## Categories of Array Manipulation
1. Attributes: Size, shape, memory consumption, data types
2. Indexing: Getting and setting value of individual array elements
3. Slicing: Getting and setting smaller subarray
4. Reshaping
5. Joining and splitting

## Attributes

In [32]:
# see for ensuring same random array are generated each time code is run
np.random.seed(0)

# array of 1D, 2D, 3d
d1 = np.random.randint(1, 10, 10)
d2 = np.random.randint(1, 10, (2, 5))
d3 = np.random.randint(1, 10, (3, 3, 1))

array([[[9],
        [5],
        [4]],

       [[1],
        [4],
        [6]],

       [[1],
        [3],
        [4]]])

In [34]:
# ndim, shape, size, dtype
print(d3.ndim)
print(d3.shape)
print(d3.size)
print(d3.dtype)

3
(3, 3, 1)
9
int32


## Indexing

In [38]:
print(d3[0])

print(d3[0, 2])   # or d3[0][2]

[[9]
 [5]
 [4]]
[4]


## Slicing

In [39]:
# x[start:stop:step]
d3[::2]

array([[[9],
        [5],
        [4]],

       [[1],
        [3],
        [4]]])

In [41]:
# for negative step, start and end are swapped
d3[::-1]

array([[[1],
        [3],
        [4]],

       [[1],
        [4],
        [6]],

       [[9],
        [5],
        [4]]])

In [42]:
# slicing + indexing
d3[:, 0]

array([[9],
       [1],
       [1]])

## Creating a Copy

In [43]:
d3.copy()

array([[[9],
        [5],
        [4]],

       [[1],
        [4],
        [6]],

       [[1],
        [3],
        [4]]])

## Reshaping

In [44]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# reshaoing with row vector via newaxis
d2[:, np.newaxis]

array([[[7, 9, 9, 2, 7]],

       [[8, 8, 9, 2, 6]]])

## Array Concatenation & Splitting
- np.concatenate(arr1, arr2)
- np.hstack(): Horizontal Stack
- np.vstack(): Vertical Stack

In [60]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
# concat along the second axis
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
# concat mixed dimensions

# vertical stack 
'''
        [x]
        
        ^
        |
        |
        |
        
       [grid]
'''
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [67]:
# concat mixed dimensions

# horizontal stack
'''

[y] <----------- [gr]
'''
y = np.array([[99], [99]])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])